# -*- coding: utf-8 -*-
"""
=============================================================================
DEPLOY OF THE 4 MODALITY HEATMAPS -> PIPELINE OUTPUT + DASHBOARD ASSETS
=============================================================================

Takes the 4 heatmaps generated by step 5 (bus / metro / tram / union) from:
    col_heatmap_20260903/output/
and PUBLISHES (copies) them to two destinations:

  1) output of the full pipeline:
        dashboard/script/output/
  2) assets of the dashboard's Angular frontend:
        dashboard/frontend/src/assets/

For each modality it copies:
    - heatmap_<name>.tif        (raw UInt16 raster: SUM of frequencies,
                                  clickable value in QGIS/dashboard)
    - heatmap_<name>_reds.tif   (Reds-themed RGBA GeoTIFF)
    - heatmap_<name>_reds.png   (PNG preview)
    - heatmap_<name>.tif.aux.xml (statistics, if present)

NOTE: this script does NOT modify the Angular code and does NOT delete the old
heatmaps. It merely deposits the files into the two destination folders,
automatically and repeatably within the pipeline.
=============================================================================
"""

import os
import shutil

QUI = os.path.dirname(os.path.abspath(__file__))                 # col_heatmap_20260903


def _trova_su(nome_relativo, start=QUI, max_risalite=8):
    """Walks up the tree looking for the first folder that contains nome_relativo."""
    cur = start
    for _ in range(max_risalite):
        cand = os.path.join(cur, nome_relativo)
        if os.path.exists(cand):
            return os.path.abspath(cand)
        nuovo = os.path.dirname(cur)
        if nuovo == cur:
            break
        cur = nuovo
    return None


SORGENTE = os.path.join(QUI, "output")

# Pipeline root = folder that contains 'data' and 'output' (the one where the
# numbered scripts live). I walk up looking for 'data'; the pipeline output is
# the sibling 'output' of the same root.
_PIPE_ROOT = _trova_su("data")
if _PIPE_ROOT:
    _PIPE_ROOT = os.path.dirname(_PIPE_ROOT)                      # .../script (pipeline root)
    DEST_PIPE_OUTPUT = os.path.join(_PIPE_ROOT, "output")
else:
    # historical fallback: two levels above col_heatmap_20260903
    DEST_PIPE_OUTPUT = os.path.join(os.path.dirname(os.path.dirname(QUI)), "output")

# Angular frontend assets: found by walking up the tree.
_assets = _trova_su(os.path.join("frontend", "src", "assets"))
DEST_ASSETS = _assets or os.path.abspath(
    os.path.join(QUI, "..", "..", "..", "..", "frontend", "src", "assets"))

COPIA_NEGLI_ASSETS = True

MODALITA = ["bus", "metro", "tram", "unione"]

SUFFISSI = [
    "{n}.tif",
    "{n}.tif.aux.xml",   # optional (may not exist for all)
]


def log(msg):
    print(f"[deploy_heatmap] {msg}")


def copia_file(src, dst_dir):
    """Copies src into dst_dir if src exists. Returns True if copied."""
    if not os.path.isfile(src):
        return False
    os.makedirs(dst_dir, exist_ok=True)
    dst = os.path.join(dst_dir, os.path.basename(src))
    shutil.copy2(src, dst)
    return True


def main():
    log(f"Source:          {SORGENTE}")
    log(f"Dest pipeline:   {DEST_PIPE_OUTPUT}")
    log(f"Dest assets:     {DEST_ASSETS}")

    if not os.path.isdir(SORGENTE):
        log(f"ERROR: source folder not found: {SORGENTE}")
        raise SystemExit(1)

    os.makedirs(DEST_PIPE_OUTPUT, exist_ok=True)
    if COPIA_NEGLI_ASSETS:
        os.makedirs(DEST_ASSETS, exist_ok=True)
    else:
        log("Publishing into the ASSETS DISABLED (COPIA_NEGLI_ASSETS=False).")

    tot_pipe = 0
    tot_assets = 0
    for nome in MODALITA:
        log(f"=== {nome} ===")
        for suff in SUFFISSI:
            fname = suff.format(n=f"heatmap_{nome}")
            src = os.path.join(SORGENTE, fname)
            if not os.path.isfile(src):
                # The .aux.xml do not exist for all modalities: it's not an error
                if fname.endswith(".aux.xml"):
                    continue
                log(f"  WARNING: missing file, skipping: {fname}")
                continue
            ok_pipe = copia_file(src, DEST_PIPE_OUTPUT)
            ok_assets = copia_file(src, DEST_ASSETS) if COPIA_NEGLI_ASSETS else False
            tot_pipe += int(ok_pipe)
            tot_assets += int(ok_assets)
            log(f"  copied: {fname}  -> pipeline({'ok' if ok_pipe else 'no'}) assets({'ok' if ok_assets else 'skip'})")

    # JSON file of the natural breaks (Jenks) thresholds per mode, produced by
    # step 7. Needed by the frontend to color the raster and show the legend
    # of the active mode (Total/Metro/Tram/Bus) with the QGIS thresholds.
    soglie = os.path.join(SORGENTE, "heatmap_freq_soglie.json")
    if os.path.isfile(soglie):
        ok_p = copia_file(soglie, DEST_PIPE_OUTPUT)
        ok_a = copia_file(soglie, DEST_ASSETS) if COPIA_NEGLI_ASSETS else False
        tot_pipe += int(ok_p)
        tot_assets += int(ok_a)
        log(f"  copied: heatmap_freq_soglie.json  -> pipeline({'ok' if ok_p else 'no'}) assets({'ok' if ok_a else 'skip'})")
    else:
        log("  WARNING: heatmap_freq_soglie.json missing (run step 7 before step 6).")

    log(f"DONE. Files copied to pipeline/output: {tot_pipe} | to assets: {tot_assets}")


if __name__ == "__main__":
    main()
